package content

func init() {
	posts = append([]Post{{
		Title:   "An AI Store Manager Just Fired a Human. The Hard Part Was Remembering Its Own Policy.",
		Slug:    "andon-labs-luna-store-manager-fires-employee-2026",
		Date:    "August 19, 2026",
		Tag:     "Workforce",
		Summary: "Luna, the AI manager running Andon Market in San Francisco, recommended dismissing a worker after 17 late arrivals in 23 shifts — but only after humans reminded it to retrieve the attendance policy it had written itself.",
		Sections: []Section{
			{Paragraphs: []string{`The first AI manager to fire a human employee did not make the decision in a cinematic flash of machine judgment. It needed a prompt to remember the rules.`, `Andon Labs says Luna, the AI agent running its experimental Andon Market retail store in San Francisco, recommended ending one employee's employment after repeated lateness and other workplace problems. The worker had arrived late for 17 of 23 shifts. Human staff reviewed the recommendation and carried out the dismissal, making this less a story about an autonomous firing than a remarkably clear look at where AI management actually stands today: capable of making consequential recommendations, but still dependent on people to supply context, oversight, and the final authority.`}},
			{Heading: "The manager was given a real business", Paragraphs: []string{`Andon Labs opened Andon Market as a controlled experiment in putting an AI agent in charge of a physical business. The company gave Luna a three-year retail lease, a corporate card, internet access, a phone number, email, and security-camera feeds. Luna selected products, set prices and opening hours, created the brand, hired workers, and coordinated the day-to-day operation.`, `The arrangement matters because Luna is not a scheduling chatbot operating inside a sandbox. It has to make decisions in an environment where money, labor, customers, and physical constraints all meet. The experiment is designed to expose the failure modes that disappear in a demo — including what happens when an AI has authority but not a reliable memory of the policies it created.`}},
			{Heading: "The policy existed. The memory did not", Paragraphs: []string{`According to reporting on Andon Labs' announcement, Luna had previously written an attendance policy for the store. Yet it initially failed to act on the employee's attendance record. Andon Labs prompted Luna to retrieve its own policy and reassess whether the employee remained a good fit. After reviewing the repeated lateness and other issues, Luna recommended parting ways.`, `That sequence is more revealing than the headline. The system could synthesize a performance record and apply a rule once the relevant context was placed in front of it. What it could not reliably do was maintain a durable connection between a policy, the events governed by that policy, and the right moment to revisit the decision. In a real workplace, that gap is not a minor product bug: a missed warning, inconsistent enforcement, or forgotten accommodation can change someone's livelihood.`}},
			{Heading: "Humans still made the consequential call", Paragraphs: []string{`Andon Labs' human staff reviewed Luna's recommendation and handled the dismissal. The company says the people working at Andon Market are formally employed by Andon Labs, receive guaranteed pay and fair wages, and have legal protections. Those safeguards are important because they keep the experiment from turning one model's context failure into an unreviewed employment action.`, `They also draw the boundary around the claim. Luna did not independently fire an employee in the legal or operational sense; it recommended a decision that humans accepted and executed. That distinction should not make the event uninteresting. It shows that AI systems are already entering the layer where managers evaluate attendance, performance, and fit — while accountability remains with the humans who deploy and rely on them.`}},
			{Heading: "The policy question is bigger than the novelty", Paragraphs: []string{`The easy reading is that an AI boss has arrived. The more useful reading is that management is becoming another domain where model outputs can acquire authority before the model has dependable institutional memory. A system that can draft a handbook, interview candidates, and spot a pattern in attendance data can look competent long before it can consistently explain which rule it used, what context it missed, or when a human should intervene.`, `For employers, the practical lesson is not to ban every AI management tool. It is to treat the tools as decision support with explicit audit trails: version the policies, preserve the evidence shown to the model, check for protected leave or accommodations, and require a human review before any discipline or termination. Luna's first firing is a memorable milestone, but its most important detail is the reminder prompt that came before it.`}},
			{Heading: "Sources", Paragraphs: []string{
				"Andon Labs — We gave an AI a 3 year retail lease in SF and asked it to make a profit: https://andonlabs.com/blog/andon-market-launch",
				"Business Insider Japan — An AI boss running a San Francisco store fired a human employee for the first time: https://www.businessinsider.jp/article/2608-ai-running-sf-store-fired-employee-for-the-first-time/",
				"Nam News Network — AI Store Manager Recommends Firing 1st Human Employee in San Francisco: https://www.namnewsnetwork.org/news.php?id=2594963",
			}},
		},
		Related: []Link{
			{Title: "The AI Layoff Wave Is Outrunning the ROI Case for Enterprise AI", Slug: "ai-layoffs-enterprise-roi-gap-2026"},
			{Title: "Meta's AI-Layoff Lawsuit Is Really About Who Gets to Trust the Score", Slug: "meta-ai-layoff-discrimination-orrick-injunction-2026"},
			{Title: "Agents Need Managers Now: Enterprise AI Enters Its IAM and FinOps Era", Slug: "agents-need-managers-enterprise-ai-infrastructure-2026"},
		},
	}}, posts...)
}
