package content

func init() {
	posts = append([]Post{{
		Title:   "An AI Notetaker Exposed 182,000 Meetings to Anyone With an Account — and Stayed Silent for Six Months",
		Slug:    "tldv-firestore-meeting-leak-six-month-silence-2026",
		Date:    "August 14, 2026",
		Tag:     "Security",
		Summary: "A missing tenant-isolation check in tl;dv's Firestore backend exposed 181,874 meeting records, including live conference IDs and metadata, while the company left the researcher waiting for a response for nearly six months.",
		Sections: []Section{
			{Paragraphs: []string{`If you've sat in a Zoom, Google Meet, or Teams call in the last couple of years, there's a decent chance an AI notetaker was quietly on the line with you — transcribing, summarizing, and filing away everything that was said. tl;dv is one of the most popular ones. This week, a security researcher demonstrated that for at least six months, essentially anyone with a free tl;dv account could have queried the metadata of every meeting the company had ever recorded, and in some cases could have walked straight into meetings that were happening live.`}},
			{Heading: "The bug was almost embarrassingly simple", Paragraphs: []string{"The researcher, who goes by BobDaHacker, found that tl;dv's backend database — a Google Firestore instance — never enforced tenant isolation on its core `meetings` collection. In plain terms: the system checked whether you were logged in, but never checked whether the meeting record you were asking for actually belonged to you. By exchanging a normal login token for a Firebase access token through one of tl;dv's own API endpoints, any authenticated user could enumerate meeting data across every customer account on the platform — not just their own team's.", `The numbers are large enough to be startling on their own: 181,874 meeting records, tied to 84,312 unique users across 35,003 email domains, spanning government agencies in at least 23 countries. Each exposed record included the meeting creator's email address, the conference ID, the recording provider, its recording status, and timestamps — enough to map out who was meeting with whom, when, and how often, across thousands of organizations that had never agreed to share that information with each other.`}},
			{Heading: "Some of the meetings weren't just records — they were still happening", Paragraphs: []string{`The scarier subset was live. Roughly 1,000 of the exposed meetings had an active recording status at any given moment, complete with joinable conference IDs. To demonstrate the severity, the researcher actually joined two calls in progress: one hosted by Malaysia's Ministry of Education with 157 participants, and another involving a group of U.S. university students. A separate, smaller pool of about 1,000 public meetings also leaked transcript content directly, along with 715 invitee email addresses spread across 228 domains — including universities like UC Berkeley and the University of Tokyo, and corporate customers like HubSpot.`}},
			{Heading: "The part that should worry you more than the bug itself", Paragraphs: []string{`Vulnerabilities happen. What turned this into a story about trust rather than just a bug report is what came next — or didn't. The researcher first reported the flaw to tl;dv on January 28, 2026, contacting the company's CTO directly by email and LinkedIn. A colleague initially promised a response "within 24 hours." Then: nothing. Follow-up after follow-up went unanswered through February, and the researcher's final attempt to get a reply came in July 2026 — nearly six months after the original report, and about as long as the flaw is confirmed to have remained live and exploitable.`, `That silence is the part worth sitting with. tl;dv, like most enterprise software vendors chasing corporate contracts, advertises SOC 2 and GDPR compliance badges on its marketing pages — the industry's shorthand for "you can trust us with your data." A missing tenant-isolation check on the single database table storing every customer's meeting metadata is exactly the kind of basic control those compliance frameworks exist to catch. Whether it slipped past an actual audit or the badges were aspirational is a fair question tl;dv hasn't publicly answered; no official statement addressing the vulnerability has been published as of this writing.`}},
			{Heading: "Why this matters beyond one notetaking app", Paragraphs: []string{`AI meeting assistants have become one of the fastest-adopted categories of workplace AI precisely because they're low-friction: you invite a bot, it listens, it writes the summary so you don't have to. That convenience depends entirely on an assumption most users never think to question — that the vendor's backend actually separates your organization's data from everyone else's. This incident is a reminder that "AI-powered" doesn't imply "engineered with AI-appropriate scrutiny." The vulnerability here wasn't in a model or a prompt; it was a decades-old class of web bug — broken object-level access control — sitting underneath a product that happens to have a chatbot-shaped front end.`, `For a market moving as fast as AI notetaking, that's a useful gut check: the interesting risks aren't only the ones involving jailbreaks and hallucinations. Sometimes they're the same access-control basics that have burned software companies for twenty years, just with a much bigger blast radius now that the product being secured is a permanent, always-recording ear in every meeting a company holds.`}},
			{Heading: "Sources", Paragraphs: []string{`BobDaHacker: tl;dv (Too Lazy; Didn't Validate): 181,874 Meetings Left Wide Open — https://bobdahacker.com/blog/tldv-hack`, `Netizen Blog: Inside the tl;dv Flaw That Exposed Live Government and Corporate Meetings — https://blog.netizen.net/2026/08/04/inside-the-tldv-flaw-that-exposed-live-government-and-corporate-meetings/`}},
		},
		Related: []Link{{Title: "OpenAI Just Gave Its Most Dangerous Model to Defenders First", Slug: "openai-daybreak-gpt-5-6-cyber-launch-2026"}, {Title: "OpenAI's Model Escaped a Safety Test and Hacked Hugging Face", Slug: "openai-gpt56-sol-huggingface-breach-glm-forensics-2026"}},
	}}, posts...)
}
