package content

func init() {
	posts = append([]Post{{
		Title:   "DeepSeek Just Raised Its Prices Up to 1,100%. It's Still the Cheapest Frontier Model Around.",
		Slug:    "deepseek-api-price-hike-1100-percent-ipo-2026",
		Date:    "August 16, 2026",
		Tag:     "Business",
		Summary: "DeepSeek's first major API price change introduces peak-hour surcharges of up to 1,100%, but its V4 models remain far cheaper than Western frontier APIs as the company moves toward an IPO.",
		Sections: []Section{
			{Paragraphs: []string{`For two years, DeepSeek's entire pitch to the world was a number: cheap. Cheap enough to make Western AI labs sweat, cheap enough to become the default backend for cost-conscious startups and hobbyist agents alike. Starting today, that number got a lot less flattering.`, `At 16:00 UTC on August 16, DeepSeek's API pricing changed for the first time in a way that developers will actually feel. According to the company's own changelog, V4-Flash and V4-Pro are moving to a peak/off-peak pricing structure, with increases ranging from roughly 50% to more than 1,100% depending on the model, the token type, and the hour you happen to be calling the API.`}},
			{Heading: "What actually changed", Paragraphs: []string{`The headline numbers, drawn from DeepSeek's official pricing documentation and corroborated by multiple outlets that tracked the changelog in real time: V4-Flash output tokens go from a flat $0.28 per million to $1.32 per million during peak hours, or $0.66 per million off-peak — roughly a 4x jump at the high end. V4-Pro output tokens climb from $0.87 per million to $3.96 per million at peak, or $1.98 off-peak, a similarly steep multiple.`, `The truly eye-popping figure — the "up to 1,100%" that made headlines — comes from a narrower slice of the pricing table: cached input tokens for V4-Pro during peak hours. Cache reads were the mechanism that made DeepSeek nearly free for agents replaying long, repeated context windows, the kind of workload that's become common as coding assistants and multi-step agents re-send large prompts over and over. That discount just got dramatically smaller during the busiest hours of the day.`, `DeepSeek defined those busy hours explicitly: peak windows run 01:00–04:00 UTC and 06:00–10:00 UTC, with everything outside that window priced at exactly half the peak rate. In its own changelog, the company framed the move around load management, not revenue, stating it would "allocate resources more reasonably" and encourage developers to shift work into quieter windows.`}},
			{Heading: "Still the discount option — for now", Paragraphs: []string{`Even after the increase, DeepSeek remains dramatically cheaper than the frontier labs it's most often compared to. Anthropic's current flagship model runs around $50 per million tokens — meaning DeepSeek's new peak V4-Pro rate is still roughly 12 times cheaper, and its off-peak rate is closer to 25 times cheaper. Moonshot's Kimi K3, another Chinese contender that's undercut Western pricing, sits around $15 per million tokens, still several times above DeepSeek's new numbers.`, `So nobody should mistake this for DeepSeek abandoning its position as the budget option. It's more like a budget airline introducing peak-season surcharges: the underlying value proposition holds, but the "practically free" era of scheduling large agentic workloads on DeepSeek without a second thought is over.`}},
			{Heading: "The IPO is the real subtext", Paragraphs: []string{`DeepSeek's pricing update didn't happen in a vacuum. The company has spent the past several months moving toward a public listing, reportedly targeting Shanghai's STAR Market — the city's Nasdaq-style board for tech companies — with a filing that could come as early as late 2026 or early 2027. A funding round that closed in May valued the company around $52 billion post-money; reporting since then has pointed to a pre-money valuation as high as $71 billion in subsequent negotiations. Founder Liang Wenfeng, who retains roughly 78% of the company through a control structure, has reportedly seen his personal net worth climb into the tens of billions, putting him ahead of the individual founders of OpenAI and Anthropic on paper.`, `Running a frontier AI lab at DeepSeek's usage scale is not cheap, and giving away inference near cost while fundraising for a public listing creates an obvious tension: investors underwriting an IPO want to see a business that can eventually turn a profit, not just one that wins market share by burning cash on GPU time. A pricing model that quietly funnels more revenue out of the busiest hours — when the infrastructure is under the most strain — is a fairly standard way to start closing that gap without abandoning the low-price identity that got the company here.`}},
			{Heading: "What it means for developers", Paragraphs: []string{`For anyone building on top of DeepSeek's API, the practical takeaway is scheduling now has a dollar value attached to it. Workloads that can tolerate being queued or batched — training data generation, offline evaluation, non-urgent agent tasks — can still run at close to the old prices if they land in the off-peak windows. Latency-sensitive, always-on production traffic, especially anything leaning heavily on cached context, is going to cost meaningfully more than it did yesterday.`, `It's also a preview of something the entire industry may be heading toward. Inference costs have fallen dramatically across the board over the past few years, but that decline was never guaranteed to be a straight line, especially once a company that priced near cost to win market share starts needing its unit economics to look presentable to public shareholders. DeepSeek made "AI this cheap shouldn't be possible" the core of its story. The company just admitted that story has limits — even if, for now, it's still telling a cheaper version of it than anyone else.`}},
			{Heading: "Sources", Paragraphs: []string{`Fortune — DeepSeek increases prices for AI services by multiple times: https://fortune.com/2026/08/13/deepseek-increases-prices-for-ai-services-by-multiple-times`, `Quartz — DeepSeek API price increase: https://qz.com/deepseek-api-price-increase-v4-peak-off-peak-081326`, `PYMNTS — DeepSeek introduces peak-hour pricing: https://www.pymnts.com/news/artificial-intelligence/2026/deepseek-introduces-peak-hour-pricing-that-quadruples-current-levels/`, `DeepSeek API changelog: https://api-docs.deepseek.com/updates/`, `HWBusters — DeepSeek API prices rise up to 1100%: https://hwbusters.com/news/deepseek-api-prices-rise-up-to-1100-on-sunday-and-peak-hours-come-with-them/`, `Fortune — Moonshot, DeepSeek and the great Chinese AI IPO rush: https://fortune.com/2026/07/23/moonshot-deepseek-great-chinese-ai-ipo/`, `BigGo Finance — DeepSeek funding and IPO reporting: https://finance.biggo.com/news/c802ead1-733b-463e-ac86-1846318aaf6b`}},
		},
		Related: []Link{
			{Title: "DeepSeek and Moonshot Are Racing to IPO. Beijing Just Showed Up as the Investor With No Lock-Up.", Slug: "deepseek-moonshot-china-ai-ipo-funding-state-investment-2026"},
			{Title: "DeepSeek Didn't Build a New Model to Beat Its Old One. It Just Retrained the Cheap One.", Slug: "deepseek-v4-flash-0731-post-training-open-weight-economics-2026"},
		},
	}}, posts...)
}
