package content

func init() {
	posts = append([]Post{{
		Title:   "Google's Gemini 3.7 Flash Beats GPT-5.6 on Coding Benchmarks. It Still Trails on the Hardest Agentic Tasks.",
		Slug:    "google-gemini-3-7-flash-coding-benchmarks-2026",
		Date:    "August 18, 2026",
		Tag:     "Models",
		Summary: "Google's newest workhorse model undercuts its own predecessor's price by half and tops rivals on several coding and enterprise-automation benchmarks, but GPT-5.6 Terra still wins the evaluations that measure whether an agent can actually finish a job end to end.",
		Sections: []Section{
			{Paragraphs: []string{`Google shipped Gemini 3.7 Flash on August 13, 2026, and the timing alone says something about where the model race has gone: this is the second Flash-tier release in three weeks, following Gemini 3.6 Flash's debut in late July. Google is no longer treating its mid-tier workhorse model as an annual event. It's treating it like a product that gets a point release whenever the numbers move.`, `This time the numbers moved quite a bit — just not uniformly.`}},
			{Heading: "Where Gemini 3.7 Flash wins", Paragraphs: []string{`On FrontierCode 1.1, the benchmark suite most closely tracking real-world production code quality, Gemini 3.7 Flash scores 43.6%, up sharply from 3.6 Flash's 34.4% just weeks earlier. That's enough to edge out both Claude Sonnet 5 (42.7%) and GPT-5.6 Terra (41.3%), putting Google's cheaper model ahead of two flagship-tier competitors on a benchmark built to resemble the kind of code engineers actually ship, not synthetic puzzle-solving.`, `The gains are even larger on tasks that look like enterprise busywork rather than competitive programming. On AutomationBench, which measures how well a model can chain together the kind of multi-step workflow automation that enterprise customers actually pay for, Gemini 3.7 Flash scores 30.4% — nearly double 3.6 Flash's 17.0%, and comfortably ahead of GPT-5.6 Terra (23.6%) and Claude (10.7%). Document comprehension follows the same pattern: 34.0% on the GDP.pdf benchmark for complex documents, up from 22.0%. On Harvey's legal-analysis benchmark (LAB-AA), it posts 90.7%, among the highest scores reported for any model on that eval. Web development output, scored by human and model preference in WebDev Arena, improved from an Elo of 1538 to 1588.`}},
			{Heading: "Where it doesn't", Paragraphs: []string{`The honest caveat, and the one Google's own announcement doesn't dwell on, is that Gemini 3.7 Flash is not the best model at the hardest agentic tasks. On DeepSWE v1.1 — a benchmark for long-horizon software engineering, where a model has to plan, execute, and correct itself across many steps rather than produce one clean function — Gemini 3.7 Flash scores 65.3%, a real jump from 3.6 Flash's 49.0%, but still behind GPT-5.6 Terra. Independent benchmark aggregation confirms the pattern holds beyond DeepSWE too: GPT-5.6 Terra continues to lead on Terminal-Bench and OSWorld, the two evals built specifically to test whether an agent can operate a real computer environment and finish a job without a human stepping in to unstick it.`, `That's a meaningful distinction for anyone actually deciding what to build with. Gemini 3.7 Flash looks excellent at writing code and chewing through documents and automations. It looks less dominant the moment the task requires sustained, semi-autonomous execution — the exact category of workload that AI coding agents and enterprise automation platforms are increasingly built around.`}},
			{Heading: "The price is already scheduled to change", Paragraphs: []string{`The other detail worth flagging sits in the fine print. Gemini 3.7 Flash launches at $0.75 per million input tokens and $3.75 per million output tokens — half of 3.6 Flash's launch pricing, and a real reason for developers to switch immediately. But that rate is explicitly introductory. Google has already published the sunset date: standard pricing of $1.50 per million input tokens and $7.50 per million output tokens takes effect January 1, 2027. The discount isn't a permanent repricing of the Flash tier; it's a four-and-a-half-month promotional window with a hard expiration already on the calendar.`, `That's not unusual for cloud AI pricing, where introductory rates are common. But it is a useful reminder for any team building cost models around Flash-tier pricing today: the number you're budgeting against this month is not the number you'll be paying in five months, and Google has been transparent enough to say so up front rather than let developers find out at the invoice.`}},
			{Heading: "The bigger pattern", Paragraphs: []string{`Gemini 3.7 Flash arrives on a 1-million-token context window, accepts text, image, video, audio, and PDF input, and offers tunable "thinking" levels — low, medium, and high — that let developers trade latency for reasoning depth on a per-request basis. None of that is radical on its own; every frontier lab now ships some version of adjustable reasoning effort. What's notable is the cadence: Google is iterating its cost-efficient tier roughly monthly, closing benchmark gaps against GPT-5.6 and Claude in specific categories one release at a time rather than waiting for a single flagship moment to reclaim the lead across the board.`, `That's a different competitive strategy than the one OpenAI and Anthropic have been running this year — big, infrequent, headline model drops paired with equally large infrastructure and funding announcements. Google is instead treating the "good enough, and cheap, and shipped last week" model as the thing worth optimizing continuously. Whether that wins developer mindshare the way a single dominant flagship model does remains an open question. But for the specific job of writing production code and automating enterprise workflows at a quarter of frontier pricing, Google just made a credible case that it doesn't need to win every benchmark to be the practical default.`}},
			{Heading: "Sources", Paragraphs: []string{
				"Google, Introducing Gemini 3.7 Flash: https://blog.google/innovation-and-ai/models-and-research/gemini-models/introducing-gemini-3-7-flash/",
				"OfficeChai, Gemini 3.7 Flash benchmarks: https://officechai.com/ai/gemini-3-7-flash-benchmarks/",
				"DataCamp, Gemini 3.7 Flash: https://www.datacamp.com/blog/gemini-3-7-flash",
				"OpenRouter, Google Gemini 3.7 Flash pricing and specifications: https://openrouter.ai/google/gemini-3.7-flash",
			}},
		},
		Related: []Link{
			{Title: "Google Just Shipped Three New Gemini Models. The One Everyone Actually Wants Still Isn't Ready.", Slug: "gemini-3-5-pro-third-delay-flash-stopgap-2026"},
			{Title: "OpenAI Just Made Its Smartest Model Run 14 Times Faster. It Didn't Make It Dumber.", Slug: "openai-ultrafast-gpt-5-6-sol-cerebras-2026"},
			{Title: "Alibaba's Qwen3.8-Max Beats GPT-5.6 and Claude on Key Benchmarks — And It's Going Open Weight", Slug: "qwen3-8-max-open-weight-benchmarks-gpt-5-6-claude-2026"},
		},
	}}, posts...)
}
