package content

func init() {
	posts = append([]Post{
		{
			Title:   "Beijing Unwound Meta's $2 Billion AI Deal. Manus Users Have Until August 23 to Save Their Data.",
			Slug:    "manus-meta-acquisition-unwind-china-ndrc-2026",
			Date:    "August 13, 2026",
			Tag:     "Policy",
			Summary: "China's NDRC ordered Meta and Manus to unwind their completed $2 billion acquisition, forcing affected users to export Meta-era data before an August 23 deletion window.",
			Sections: []Section{
				{Paragraphs: []string{
					"Eight months ago, Meta closed one of the more interesting acquisitions in the agentic AI space: a $2 billion deal for Manus, the Singapore-based startup whose autonomous agent could browse the web, book things, and finish multi-step tasks with minimal hand-holding. This week, that deal came apart, and not because either party wanted out.",
					"On Tuesday, August 11, Manus told its users it will \"soon operate independently again,\" completing a separation from Meta that neither company chose. The real story sits with China's National Development and Reform Commission, the state planning body that in April ordered the transaction unwound entirely, ruling that it violated Chinese law governing outbound investment, technology exports, and cross-border data transfers.",
				}},
				{Heading: "A deal that never really finished", Paragraphs: []string{
					"Meta's acquisition of Manus closed on December 29, 2025. It looked, at the time, like a straightforward bet: Meta wanted a working agentic product it didn't have to build from scratch, and Manus wanted the compute and distribution that come with being owned by one of the largest AI spenders on Earth. But Manus has Chinese engineering roots, even though it is incorporated in Singapore, and that combination put the deal squarely in the path of Beijing's tightening rules on how domestic AI technology and talent can be sold abroad.",
					"China's Ministry of Commerce had signaled this coming as early as January, stating that companies engaged in \"outbound investment, technology exports, cross-border data transfers, and mergers and acquisitions\" involving Chinese-linked AI assets must comply with Chinese law, regardless of where the company is formally headquartered. Regulators have increasingly scrutinized what analysts call \"Singapore-washing\" — relocating a company's legal home to sidestep the export and investment rules that would otherwise apply to a Chinese-founded AI business. By April, the NDRC had made its decision: the Meta-Manus deal did not comply, and it ordered the parties to unwind it.",
					"Meta's position is that it did nothing wrong. The company says the transaction \"complied fully with applicable law\" when it was signed. Manus, caught in the middle, framed its return to independence more diplomatically: the company said it \"must take this step to comply with regulatory requirements in specific parts of the world.\"",
				}},
				{Heading: "What happens to your data", Paragraphs: []string{
					"For Manus users, the unwind isn't just a corporate footnote — it comes with a hard deadline. According to the company's own notice, users have a backup window running from August 11 through August 23 to export anything they want to keep. Then, starting at 8:00 a.m. Singapore time on August 23 and running through August 24, Manus will delete data generated by \"certain users\" — specifically, data created on or after December 29, 2025, the day Meta's acquisition closed. Account access will be unavailable during the deletion window itself, with normal service, including a welcome-back bonus for affected users, expected to resume on August 25.",
					"The scope is narrower than a full wipe: the deletion applies to specific regulatory jurisdictions and to data tied to the Meta-era period of the product, not the entirety of Manus's history. Still, it's a rare real-world example of geopolitics reaching directly into a consumer AI product's storage layer, with a clock that ordinary users now have to watch.",
				}},
				{Heading: "Why this is bigger than one acquisition", Paragraphs: []string{
					"It would be easy to file this under corporate housekeeping, but the timing says otherwise. This is the same year the U.S. accused Chinese lab Moonshot of distilling Anthropic's Claude to help train its Kimi K3 model, the same year the world's two largest AI powers formalized competing technology alliances rather than a shared one, and now the same year Beijing has demonstrated it will reverse a completed, paid-for acquisition of a Chinese-rooted AI company on national-security grounds. Export controls on chips got most of the attention over the past two years. What the Manus case shows is that the control point is shifting up the stack, from silicon to the agents and models built on top of it, and from hardware sales to outright ownership of AI companies themselves.",
					"As analyst Wendy Chang put it, the message to Chinese tech leaders is that \"attempts to bypass national regulation will not be tolerated\" — and the message to foreign acquirers, implicitly, is that a signed check and a closed deal are no longer guarantees of a deal that stays closed. For an industry that has treated cross-border AI acquisitions as routine business, that's a genuinely new kind of risk to price in.",
				}},
				{Heading: "Sources", Paragraphs: []string{
					"Manus official notice: https://manus.im/blog/a-note-to-our-users",
					"CNBC: https://www.cnbc.com/2026/08/11/manus-china-meta-acquisition.html",
					"China Daily: https://www.chinadaily.com.cn/a/202608/12/WS6a7c0573a310986e2b46a5a8.html",
					"Bloomberg: https://www.bloomberg.com/news/articles/2026-08-11/manus-to-resume-independent-operations-in-unwind-of-meta-deal",
				}},
			},
			Related: []Link{
				{Title: "The White House Says China Cloned Claude to Build Kimi K3", Slug: "white-house-moonshot-kimi-k3-anthropic-fable-distillation-2026"},
				{Title: "Two AI Superpowers Just Built Rival Alliances", Slug: "two-ai-superpowers-rival-alliances-one-country-joined-both-2026"},
			},
		},
	}, posts...)
}
